name: Deploy Polly App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Lambda package
        run: |
          mkdir -p deploy
          zip -j deploy/api.zip lambda/api.py

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -upgrade

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        timeout-minutes: 30

      - name: Update website with API URL
        run: |
          WEBSITE_BUCKET=$(cd terraform && terraform output -raw website_bucket)
          sed -i 's|https://q7dnar5wh8.execute-api.us-east-1.amazonaws.com/prod|https://q7dnar5wh8.execute-api.us-east-1.amazonaws.com/prod|g' website/scripts.js
          aws s3 cp website/scripts.js s3://$WEBSITE_BUCKET/scripts.js --content-type "application/javascript"
          