name: Deploy Polly App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Lambda deployment package
        run: |
          mkdir -p deploy
          zip -j deploy/api.zip lambda/api.py

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Import existing resources
        working-directory: terraform
        run: |
          terraform import aws_dynamodb_table.posts content_posts || true
          terraform import aws_s3_bucket.audio audio-storage-bucket-unique-2025 || true

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        timeout-minutes: 30